/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.ijse.inventory.views;

import lk.ijse.inventory.controller.OrderFormController;
import lk.ijse.inventory.dto.CustomerDTO;
import lk.ijse.inventory.dto.OrderDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.inventory.dto.OrderDetailDTO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class manageCustomerOrders extends javax.swing.JFrame {

    /**
     * Creates new form manageCustomerOrders
     */
    public manageCustomerOrders() {
        initComponents();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCustomers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemDetails = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOID = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CustomerOrdersManage");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 440, 50));

        cmbCustomers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustomersItemStateChanged(evt);
            }
        });
        cmbCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCustomersMouseClicked(evt);
            }
        });
        jPanel1.add(cmbCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 310, 50));

        jLabel2.setText("Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        tblItemDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ItemCode", "qty", "unitPrice"
            }
        ));
        jScrollPane1.setViewportView(tblItemDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 700, 220));

        tblOID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "oid"
            }
        ));
        tblOID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOIDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblOID);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCustomersMouseClicked
        
        
    }//GEN-LAST:event_cmbCustomersMouseClicked

    private void cmbCustomersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustomersItemStateChanged

try {
            String selectedCustomerID = cmbCustomers.getSelectedItem().toString();
            CustomerDTO searchCustomer = new OrderFormController().searchCustomer(selectedCustomerID);
            if (searchCustomer != null) {
                 DefaultTableModel dtm = (DefaultTableModel) tblOID.getModel();
                dtm.setRowCount(0);
            try {
             ArrayList<OrderDTO> allOrders = new OrderFormController().getAllOrdersbycusCode(selectedCustomerID);

                        for (OrderDTO i : allOrders) {
                            Object[] row = {i.getOid()};
                            dtm.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
            }

        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
    }//GEN-LAST:event_cmbCustomersItemStateChanged

    private void tblOIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOIDMouseClicked
          try {
//            String selectedOrderID = cmbCustomerOID.getSelectedItem().toString();
            int selectdorder = tblOID.getSelectedRow();
              TableModel model =tblOID.getModel();
              String oid = (String) model.getValueAt(selectdorder,0);
              OrderDTO searchOrder = new OrderFormController().searchOrder(oid);
            if (searchOrder != null) {
                DefaultTableModel dtm = (DefaultTableModel) tblItemDetails.getModel();
                dtm.setRowCount(0);
                try {
                   
                        ArrayList<OrderDetailDTO> allOrdersdetails = new OrderFormController().getAllItemsbyorderID(oid);

                        for (OrderDetailDTO i : allOrdersdetails) {
                            Object[] row = {i.getItemCode(), i.getQty(), i.getUnitPrice()};
                            dtm.addRow(row);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        
    
        
        
    }//GEN-LAST:event_tblOIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageCustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageCustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageCustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageCustomerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageCustomerOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCustomers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblItemDetails;
    private javax.swing.JTable tblOID;
    // End of variables declaration//GEN-END:variables

    private void loadAllCustomers() {
         try {
            ArrayList<CustomerDTO> allCustomers = new OrderFormController().getAllCustomers();
            cmbCustomers.removeAllItems();
            for (CustomerDTO customer : allCustomers) {
              cmbCustomers.addItem(customer.getCustomerID());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    }

