/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.ijse.inventory.views;
import lk.ijse.inventory.controller.ItemFormController;
import lk.ijse.inventory.controller.OrderFormController;
import lk.ijse.inventory.dto.CustomerDTO;
import lk.ijse.inventory.dto.ItemDTO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tharaka Dasunpriya
 */
public class OrderForm extends javax.swing.JFrame {
         DefaultTableModel dtm;
    /**
     * Creates new form orderForm
     */
    public OrderForm() {
        initComponents();
        setDate();
        dtm = (DefaultTableModel) tblOrders.getModel();
        loadAllCustomers();
        loadAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtcusAddress = new javax.swing.JTextField();
        txtOrderDate = new javax.swing.JTextField();
        txtCusName = new javax.swing.JTextField();
        txtCusID = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtCusSalary = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbCusID = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        txtItemUnitPrice = new javax.swing.JTextField();
        txtItemQty = new javax.swing.JTextField();
        txtBuyQty = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        cmbSearchItem = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAddRow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Make the Customer Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 330, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 170, -1));
        jPanel1.add(txtcusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, -1));
        jPanel1.add(txtOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 150, -1));
        jPanel1.add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 180, -1));
        jPanel1.add(txtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, -1));
        jPanel1.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 170, -1));
        jPanel1.add(txtCusSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 170, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        jLabel2.setText("order Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 80, -1));

        jLabel3.setText("order Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        jLabel4.setText("Search Item");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 80, -1));

        jLabel5.setText("Select Customer");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, -1));

        jLabel6.setText("CID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 80, -1));

        jLabel7.setText("Csalary");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 80, -1));

        jLabel8.setText("CAddress");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, -1));

        cmbCusID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCusIDItemStateChanged(evt);
            }
        });
        cmbCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCusIDActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, -1));

        jLabel9.setText("CName");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 80, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 160, -1));
        jPanel1.add(txtItemUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 200, -1));
        jPanel1.add(txtItemQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 150, -1));

        txtBuyQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyQtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuyQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 170, -1));
        jPanel1.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 150, -1));

        cmbSearchItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSearchItemItemStateChanged(evt);
            }
        });
        cmbSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchItemActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSearchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 160, -1));

        jLabel10.setText("order Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 80, -1));

        jLabel11.setText("ItemCode");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, -1));

        jLabel12.setText("itemQTyOnHand");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, -1));

        jLabel13.setText("order Date");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, -1));

        jLabel14.setText("itemUnitprice");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 110, -1));

        jLabel16.setText("BuyQty");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 80, -1));

        jLabel17.setText("ItemName");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 80, -1));

        btnAddRow.setText("Add Row");
        btnAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRowActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "itemCode ", "itemName", "Qty", "UnitPrice", "itemTotal"
            }
        ));
        jScrollPane1.setViewportView(tblOrders);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 740, 190));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCusIDActionPerformed

    private void cmbCusIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCusIDItemStateChanged
         try {
            String selectedCustomerID = cmbCusID.getSelectedItem().toString();
            CustomerDTO searchCustomer = new OrderFormController().searchCustomer(selectedCustomerID);
            if (searchCustomer != null) {
                txtCusID.setText(searchCustomer.getCustomerID());
                txtCusName.setText(searchCustomer.getCustomerName());
                txtcusAddress.setText(searchCustomer.getCustomerAddress());
                txtCusSalary.setText(searchCustomer.getCustomerSalary()+ "");
            }

        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCusIDItemStateChanged

    private void cmbSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchItemActionPerformed

    private void cmbSearchItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSearchItemItemStateChanged
         String selectedItem = cmbSearchItem.getSelectedItem().toString();
             try {
                 ItemDTO searchitem = new ItemFormController().searchItem(selectedItem);
                 if (searchitem != null) {
                     txtItemCode.setText(searchitem.getItemCode());
                     txtItemName.setText(searchitem.getItemName());
                     txtItemQty.setText(searchitem.getQty()+"");
                     txtItemUnitPrice.setText(searchitem.getUnitPrice()+"");
           
                 }
 
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
             }
        
    }//GEN-LAST:event_cmbSearchItemItemStateChanged

    private void txtBuyQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyQtyActionPerformed

    private void btnAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRowActionPerformed
        String itemCode= cmbSearchItem.getSelectedItem().toString();
        String itemName= txtItemName.getText();
        int buyQty = Integer.parseInt(txtBuyQty.getText());
        double unitPrice = Double.parseDouble(txtItemUnitPrice.getText());
        double total  = unitPrice*buyQty;
        
        Object[] row = {itemCode,itemName,buyQty,unitPrice,total};
                dtm.addRow(row);
        
    }//GEN-LAST:event_btnAddRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JComboBox<String> cmbCusID;
    private javax.swing.JComboBox<String> cmbSearchItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtBuyQty;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusSalary;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemQty;
    private javax.swing.JTextField txtItemUnitPrice;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtcusAddress;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
     String Date= LocalDate.now().toString();
     txtOrderDate.setText(Date);
    }

    private void loadAllCustomers() {
      try {
            ArrayList<CustomerDTO> allCustomers = new OrderFormController().getAllCustomers();
            cmbCusID.removeAllItems();
            for (CustomerDTO customer : allCustomers) {
                cmbCusID.addItem(customer.getCustomerID());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItems(){
             try {
                 cmbSearchItem.removeAllItems();
                 ArrayList<ItemDTO> allItems= new ItemFormController().getAllItem();
                 for(ItemDTO item:allItems){
                     cmbSearchItem.addItem(item.getItemCode());
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
             }
        
    }
        
    }

